from __future__ import annotations

from typing import Any

NIVOLUMAB: dict[str, Any] = {
    "molecule_name": "nivolumab",
    "reference_brand": "Opdivo",
    "manufacturer": "Bristol-Myers Squibb",
    "search_terms": [
        "nivolumab biosimilar",
        "ABP 206",
        "HLX18",
        "Tishtha",
        "Xdivane",
        "BA1104",
        "JPB898",
        "MB11",
    ],
    "indications": {
        "NSCLC": {
            "priority": "HIGH",
            "market_size_usd_b": 2.8,
            "pivotal": True,
        },
        "Melanoma": {
            "priority": "HIGH",
            "market_size_usd_b": 1.2,
            "pivotal": True,
        },
        "RCC": {
            "priority": "MEDIUM",
            "market_size_usd_b": 0.8,
            "pivotal": False,
        },
        "SCCHN": {
            "priority": "MEDIUM",
            "market_size_usd_b": 0.4,
            "pivotal": False,
        },
        "ESCC": {
            "priority": "MEDIUM",
            "market_size_usd_b": 0.3,
            "pivotal": False,
        },
    },
    "loe_timeline": {
        "India": {
            "date": "2026-05-02",
            "multiplier": 2.0,
            "status": "OPEN",
        },
        "US": {
            "date": "2028-01-01",
            "multiplier": 1.5,
            "status": "APPROACHING",
        },
        "EU": {
            "date": "2029-07-01",
            "multiplier": 1.1,
            "status": "MONITOR",
        },
        "Japan": {
            "date": "2030-04-01",
            "multiplier": 0.6,
            "status": "LONG_HORIZON",
        },
        "China": {
            "date": "2028-01-01",
            "multiplier": 0.9,
            "status": "MONITOR",
        },
    },
    "competitor_universe": [
        "Amgen",
        "Zydus",
        "Sandoz",
        "Xbrane",
        "Intas",
        "Boan Biotech",
        "Henlius",
        "mAbxience",
        "Reliance Life Sciences",
        "Enzene",
        "Dr. Reddy's",
        "Biocon Biologics",
        "NeuClone",
    ],
    "scoring_weights": {},
    "is_active": True,
}

COMPETITORS: list[dict[str, Any]] = [
    {
        "canonical_name": "Amgen",
        "tier": 1,
        "asset_code": "ABP 206",
        "development_stage": "phase_3",
        "status": "active",
        "primary_markets": ["US", "EU"],
        "launch_window": "~2028",
        "parent_company": "Amgen",
        "partnership_status": "solo",
        "cik": "0000318154",
    },
    {
        "canonical_name": "Zydus",
        "tier": 1,
        "asset_code": "Tishtha",
        "development_stage": "launched",
        "status": "active",
        "primary_markets": ["India"],
        "launch_window": "Live Jan 2026",
        "price_position": "~25% originator",
        "parent_company": "Zydus Lifesciences",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Xbrane",
        "tier": 2,
        "asset_code": "Xdivane",
        "development_stage": "phase_1_2",
        "status": "active",
        "primary_markets": ["US", "EU"],
        "launch_window": "US Dec 2028, EU Jun 2030",
        "parent_company": "Xbrane Biopharma",
        "partnership_status": "partnership",
    },
    {
        "canonical_name": "Intas",
        "tier": 2,
        "asset_code": "Xdivane",
        "development_stage": "phase_1_2",
        "status": "active",
        "primary_markets": ["US", "EU"],
        "launch_window": "US Dec 2028, EU Jun 2030",
        "parent_company": "Intas Pharmaceuticals",
        "partnership_status": "partnership",
    },
    {
        "canonical_name": "Boan Biotech",
        "tier": 2,
        "asset_code": "BA1104",
        "development_stage": "phase_3",
        "status": "active",
        "primary_markets": ["China"],
        "launch_window": "~2027-2028",
        "parent_company": "Boan Biotech",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Sandoz",
        "tier": 2,
        "asset_code": "JPB898",
        "development_stage": "suspended",
        "status": "active",
        "primary_markets": ["US", "EU"],
        "launch_window": "TBD",
        "parent_company": "Novartis",
        "partnership_status": "solo",
        "cik": "0000718877",
    },
    {
        "canonical_name": "Henlius",
        "tier": 3,
        "asset_code": "HLX18",
        "development_stage": "phase_1",
        "status": "active",
        "primary_markets": ["Global"],
        "launch_window": "Post-2028",
        "parent_company": "Shanghai Henlius",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "mAbxience",
        "tier": 3,
        "asset_code": "MB11",
        "development_stage": "phase_3",
        "status": "active",
        "primary_markets": ["Global"],
        "launch_window": "Post-2028",
        "parent_company": "mAbxience",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Reliance Life Sciences",
        "tier": 3,
        "asset_code": None,
        "development_stage": "phase_1_2",
        "status": "active",
        "primary_markets": ["India"],
        "launch_window": "Post-2027",
        "parent_company": "Reliance Industries",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Enzene",
        "tier": 3,
        "asset_code": None,
        "development_stage": "phase_3",
        "status": "active",
        "primary_markets": ["India"],
        "launch_window": "Post-2027",
        "parent_company": "Enzene Biosciences",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Dr. Reddy's",
        "tier": 4,
        "asset_code": None,
        "development_stage": "pre_clinical",
        "status": "active",
        "primary_markets": ["India", "Global"],
        "launch_window": "TBD",
        "parent_company": "Dr. Reddy's Laboratories",
        "partnership_status": "solo",
        "cik": "0000895417",
    },
    {
        "canonical_name": "Biocon Biologics",
        "tier": 4,
        "asset_code": None,
        "development_stage": "pre_clinical",
        "status": "active",
        "primary_markets": ["India", "Global"],
        "launch_window": "TBD",
        "parent_company": "Biocon",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "NeuClone",
        "tier": 4,
        "asset_code": None,
        "development_stage": "pre_clinical",
        "status": "active",
        "primary_markets": ["Global"],
        "launch_window": "TBD",
        "parent_company": "NeuClone",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Mabpharm",
        "tier": 4,
        "asset_code": "CMAB 819",
        "development_stage": "terminated",
        "status": "active",
        "primary_markets": [],
        "launch_window": "N/A",
        "parent_company": "Mabpharm",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Beacon Medicare",
        "tier": 4,
        "asset_code": None,
        "development_stage": "watch",
        "status": "active",
        "primary_markets": [],
        "launch_window": "TBD",
        "parent_company": "Beacon Medicare",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Farmazona",
        "tier": 4,
        "asset_code": None,
        "development_stage": "watch",
        "status": "active",
        "primary_markets": ["LATAM"],
        "launch_window": "TBD",
        "parent_company": "Farmazona",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Farmacam S.A",
        "tier": 4,
        "asset_code": None,
        "development_stage": "watch",
        "status": "active",
        "primary_markets": ["LATAM"],
        "launch_window": "TBD",
        "parent_company": "Farmacam S.A",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "Lupin",
        "tier": 4,
        "asset_code": None,
        "development_stage": "watch",
        "status": "active",
        "primary_markets": ["India"],
        "launch_window": "TBD",
        "parent_company": "Lupin Limited",
        "partnership_status": "solo",
    },
    {
        "canonical_name": "CinnaGen",
        "tier": 4,
        "asset_code": None,
        "development_stage": "watch",
        "status": "active",
        "primary_markets": [],
        "launch_window": "TBD",
        "parent_company": "CinnaGen",
        "partnership_status": "solo",
    },
]
