"""add sec_filings table

Revision ID: 5853b13607d0
Revises: 000000000001
Create Date: 2026-04-22 22:01:44.897124

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5853b13607d0'
down_revision: str | None = '000000000001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sec_filings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('filing_date', sa.DateTime(), nullable=False),
    sa.Column('accession_number', sa.String(length=50), nullable=False),
    sa.Column('primary_doc_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_sec_filings_cik'), 'sec_filings', ['cik'], unique=False)
    op.create_index(op.f('ix_sec_filings_competitor_id'), 'sec_filings', ['competitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sec_filings_competitor_id'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_cik'), table_name='sec_filings')
    op.drop_table('sec_filings')
    # ### end Alembic commands ###
