"""add_combo_tracking

Revision ID: c6362beb3933
Revises: 356849a3d003
Create Date: 2026-04-25 15:20:54.183489

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6362beb3933'
down_revision: str | None = '356849a3d003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecule_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primary_molecule_id', sa.UUID(), nullable=False),
    sa.Column('secondary_molecule_id', sa.UUID(), nullable=False),
    sa.Column('combo_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['primary_molecule_id'], ['molecules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secondary_molecule_id'], ['molecules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_molecule_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('molecule_id', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(length=100), nullable=False),
    sa.Column('development_stage', sa.String(length=50), nullable=True),
    sa.Column('is_primary_focus', sa.Boolean(), nullable=True),
    sa.Column('combo_capability', sa.Enum('FULL', 'PARTIAL', 'NONE', name='combo_capability'), nullable=False),
    sa.Column('has_clinical_trial_for_combo', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['molecule_id'], ['molecules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'molecule_id', name='uq_competitor_molecule')
    )
    op.add_column('molecules', sa.Column('inn', sa.String(length=100), nullable=True))
    op.add_column('molecules', sa.Column('brand_name', sa.String(length=100), nullable=True))
    op.add_column('molecules', sa.Column('mechanism_of_action', sa.String(length=200), nullable=True))
    op.add_column('molecules', sa.Column('therapeutic_area', sa.String(length=100), nullable=True))
    op.add_column('molecules', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('molecules', sa.Column('is_reference_product', sa.Boolean(), nullable=True))
    op.create_unique_constraint('uq_molecules_inn', 'molecules', ['inn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_molecules_inn', 'molecules', type_='unique')
    op.drop_column('molecules', 'is_reference_product')
    op.drop_column('molecules', 'status')
    op.drop_column('molecules', 'therapeutic_area')
    op.drop_column('molecules', 'mechanism_of_action')
    op.drop_column('molecules', 'brand_name')
    op.drop_column('molecules', 'inn')
    op.drop_table('competitor_molecule_assignments')
    op.drop_table('molecule_pairs')
    sa.Enum('FULL', 'PARTIAL', 'NONE', name='combo_capability').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
