"""add_geo_intelligence_tables

Revision ID: 356849a3d003
Revises: 4e3aed1cc707
Create Date: 2026-04-25 15:05:17.733155

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '356849a3d003'
down_revision: str | None = '4e3aed1cc707'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Enum('CEE_EU', 'LATAM', 'MEA', name='region_code'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('operating_model', sa.Enum('LPM', 'OPM', 'Passive', name='operating_model'), nullable=False),
    sa.Column('local_regulatory_agency_name', sa.String(length=100), nullable=True),
    sa.Column('local_currency_code', sa.String(length=3), nullable=True),
    sa.Column('ema_parallel_recognition', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('competitor_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('has_local_manufacturing', sa.Boolean(), nullable=True),
    sa.Column('has_local_regulatory_filing', sa.Boolean(), nullable=True),
    sa.Column('has_local_commercial_infrastructure', sa.Boolean(), nullable=True),
    sa.Column('local_partner_name', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitor_capabilities')
    op.drop_table('countries')
    op.drop_table('regions')
    sa.Enum('CEE_EU', 'LATAM', 'MEA', name='region_code').drop(op.get_bind(), checkfirst=True)
    sa.Enum('LPM', 'OPM', 'Passive', name='operating_model').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
