"""add_social_media_noise

Revision ID: 674edc2375a3
Revises: 63533aa7df89
Create Date: 2026-04-26 15:48:05.117546

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '674edc2375a3'
down_revision: Union[str, None] = '63533aa7df89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_platform', sa.String(length=20), nullable=False),
    sa.Column('post_url', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('matched_keywords', sa.Text(), nullable=True),
    sa.Column('molecule_id', sa.UUID(), nullable=True),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('noise_signal_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['molecule_id'], ['molecules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['noise_signal_id'], ['noise_signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_media_raw_noise_signal_id', 'social_media_raw', ['noise_signal_id'], unique=False)
    op.create_index('ix_social_media_raw_source_platform_published_date', 'social_media_raw', ['source_platform', 'published_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_media_raw_source_platform_published_date', table_name='social_media_raw')
    op.drop_index('ix_social_media_raw_noise_signal_id', table_name='social_media_raw')
    op.drop_table('social_media_raw')
    # ### end Alembic commands ###
